"""Builds a single status page from the logs, for checking the desk from a phone.

Everything here is read from files the system already writes — positions, decisions, risk
policies, journal, watch state — so the page is a faithful snapshot rather than a second source
of truth. It is generated by code and published as a static page: it shows the moment it was
built, and the build time is stated at the top so a stale page cannot be mistaken for a live one.

Run: `python status_page.py` (writes status.html and prints the path).
"""

import datetime as dt
import html
import json
import os
import sys

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
if __name__ == "__main__":
    os.chdir(PROJECT_DIR)
    sys.path.insert(0, PROJECT_DIR)

import journal  # noqa: E402
import market_context  # noqa: E402
import opportunity_watch  # noqa: E402
import portfolio_store  # noqa: E402
import positions_store  # noqa: E402
import risk_policy  # noqa: E402
import scorecard  # noqa: E402
from config import settings  # noqa: E402

OUT_PATH = os.path.join(PROJECT_DIR, "status.html")


def _positions() -> list:
    rows = []
    held, _updated = positions_store.load()
    for symbol, (quantity, _sellable) in sorted(held.items()):
        if quantity <= 0:
            continue
        stats = market_context.stats(symbol) or {}
        entry = (scorecard._last_buy(symbol) or {}).get("price")
        price = stats.get("price")
        value = (price or 0) * quantity
        move = ((price - entry) / entry) if (price and entry) else None
        rows.append({"symbol": symbol, "quantity": quantity, "price": price, "entry": entry,
                     "value": value, "move": move})
    return sorted(rows, key=lambda row: -row["value"])


def _today_runs() -> list:
    today = dt.datetime.now(dt.timezone.utc).date().isoformat()
    out = []
    for entry in journal.recent(40):
        if entry["timestamp"][:10] != today:
            continue
        orders = "; ".join(f"{o.get('side')} {o.get('symbol')} ${o.get('dollars')}"
                           for o in entry.get("orders") or []) or "no orders"
        out.append({"at": entry["timestamp"][11:16], "mode": entry.get("mode", ""), "orders": orders,
                    "summary": (entry.get("summary") or "").strip()})
    return out[-6:]


def _score_rows() -> list:
    result = scorecard.score()
    return [{"horizon": f"{days}d", **stats} for days, stats in sorted(result.get("horizons", {}).items())]


def build() -> str:
    now = dt.datetime.now().astimezone()
    snapshot = portfolio_store.load()
    limits = risk_policy.effective()
    policy = risk_policy.today()
    positions = _positions()
    crypto_value = sum(row["value"] for row in positions)
    setups = opportunity_watch.setups()
    runs = _today_runs()
    scores = _score_rows()
    decisions = [d for d in scorecard.decisions() if not d.get("forced")]
    realised = len([d for d in decisions if d.get("side") == "sell"])

    esc = html.escape

    def pct(value, digits=1):
        return f"{value:+.{digits}%}" if value is not None else "n/a"

    parts = ["""<title>Desk Status</title>
<style>
:root{--bg:#0F1412;--card:#18201D;--ink:#E6EDE9;--soft:#94A39C;--line:#28332E;--up:#4BC58F;--down:#E4785F;--accent:#C9A227}
@media (prefers-color-scheme: light){:root:not([data-theme="dark"]){--bg:#F4F6F4;--card:#FFFFFF;--ink:#16211C;--soft:#5D6B64;--line:#DCE3DE;--up:#137A52;--down:#B4432F;--accent:#8A6D10}}
:root[data-theme="light"]{--bg:#F4F6F4;--card:#FFFFFF;--ink:#16211C;--soft:#5D6B64;--line:#DCE3DE;--up:#137A52;--down:#B4432F;--accent:#8A6D10}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",system-ui,sans-serif;padding:20px 14px 48px}
.wrap{max-width:720px;margin:0 auto;display:grid;gap:16px}
h1{font-size:22px;margin:0;letter-spacing:-.01em}
.built{font:12px ui-monospace,Consolas,monospace;color:var(--soft)}
.card{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:14px 16px;display:grid;gap:10px}
.card h2{margin:0;font-size:12px;letter-spacing:.1em;text-transform:uppercase;color:var(--soft);font-weight:600}
.big{display:flex;flex-wrap:wrap;gap:18px;align-items:baseline}
.big b{font-size:30px;font-weight:700;letter-spacing:-.02em;font-variant-numeric:tabular-nums}
.big span{color:var(--soft);font:13px ui-monospace,Consolas,monospace}
table{width:100%;border-collapse:collapse;font:13.5px ui-monospace,Consolas,monospace}
th{text-align:left;font-size:10.5px;letter-spacing:.08em;text-transform:uppercase;color:var(--soft);padding:0 0 6px;font-weight:600}
td{padding:6px 0;border-top:1px solid var(--line);font-variant-numeric:tabular-nums}
td.r,th.r{text-align:right}
.up{color:var(--up)}.down{color:var(--down)}
.pill{display:inline-block;font:11px ui-monospace,Consolas,monospace;padding:3px 7px;border-radius:999px;border:1px solid var(--line);color:var(--soft)}
.run{border-top:1px solid var(--line);padding-top:9px;display:grid;gap:3px}
.run b{font:12px ui-monospace,Consolas,monospace;color:var(--accent)}
.run p{margin:0;font-size:13px;color:var(--soft)}
.setup{font-size:13.5px}
.setup b{font-family:ui-monospace,Consolas,monospace}
.none{color:var(--soft);font-size:13.5px}
</style>
<div class="wrap">"""]

    parts.append(f'<div><h1>Desk status</h1><div class="built">built {esc(now.strftime("%a %d %b, %I:%M %p %Z"))} '
                 f'· snapshot, not live</div></div>')

    cash = snapshot.get("crypto_buying_power")
    held_at = positions_store.load()[1]
    held_age = ""
    if held_at:
        minutes = (dt.datetime.now(dt.timezone.utc) - dt.datetime.fromisoformat(held_at)).total_seconds() / 60
        held_age = (f"{minutes:.0f} min" if minutes < 90 else f"{minutes / 60:.0f} h") + " old"
    # Quantities and cash both come from the last cycle, so the page states their age rather
    # than adding them into a total that would read as the live account value.
    if cash is not None:
        headline, note = f"${crypto_value + cash:,.2f}", f"cash ${cash:,.2f}"
    else:
        headline, note = f"${crypto_value:,.2f}", "cash unknown until the next cycle"
    parts.append('<div class="card"><h2>Account</h2><div class="big">'
                 f'<b>{headline}</b>'
                 f'<span>crypto ${crypto_value:,.2f}</span>'
                 f'<span>{esc(note)}</span>'
                 f'<span>{len(positions)} positions</span></div>'
                 f'<div class="none">Holdings as the broker last reported them'
                 f'{" · " + esc(held_age) if held_age else ""}. Prices are daily closes, not live quotes.</div>'
                 '</div>')

    if positions:
        rows = "".join(
            f'<tr><td>{esc(row["symbol"])}</td><td class="r">${row["value"]:,.2f}</td>'
            f'<td class="r">{("$%.4f" % row["price"]) if row["price"] else "n/a"}</td>'
            f'<td class="r {"up" if (row["move"] or 0) >= 0 else "down"}">{pct(row["move"])}</td></tr>'
            for row in positions)
        parts.append('<div class="card"><h2>Positions</h2><table><tr><th>pair</th><th class="r">value</th>'
                     f'<th class="r">price</th><th class="r">vs entry</th></tr>{rows}</table></div>')

    source = "risk agent" if limits.agent_set else "fixed fallback"
    stance = (policy or {}).get("stance", "")
    parts.append('<div class="card"><h2>Limits today</h2>'
                 f'<div><span class="pill">{esc(source)}{" · " + esc(stance) if stance else ""}</span></div>'
                 f'<table><tr><td>order size</td><td class="r">{limits.per_order_pct:.0%}</td>'
                 f'<td>per pair</td><td class="r">{limits.max_position_pct:.0%}</td></tr>'
                 f'<tr><td>per theme</td><td class="r">{limits.max_theme_pct:.0%}</td>'
                 f'<td>trades today</td><td class="r">{limits.max_trades_today}</td></tr>'
                 f'<tr><td>volatility target</td><td class="r">{limits.vol_target_pct:.1%}</td>'
                 f'<td>cooldown</td><td class="r">{limits.cooldown_hours:.0f}h</td></tr>'
                 f'<tr><td>max spread</td><td class="r">{limits.max_spread_pct:.1%}</td>'
                 f'<td>loss breaker</td><td class="r">{settings.max_daily_loss_pct:.0%}</td></tr></table></div>')

    if runs:
        items = "".join(f'<div class="run"><b>{esc(r["at"])} UTC · {esc(r["mode"])} · {esc(r["orders"])}</b>'
                        f'<p>{esc(r["summary"][:260])}</p></div>' for r in runs)
        parts.append(f'<div class="card"><h2>Today’s runs</h2>{items}</div>')
    else:
        parts.append('<div class="card"><h2>Today’s runs</h2><div class="none">No runs recorded today.</div></div>')

    if setups:
        items = "".join(f'<div class="setup"><b>{esc(row["symbol"])}</b> — {esc("; ".join(row["reasons"]))}</div>'
                        for row in setups)
        parts.append(f'<div class="card"><h2>Setups the watch sees</h2>{items}</div>')
    else:
        parts.append('<div class="card"><h2>Setups the watch sees</h2>'
                     '<div class="none">Nothing tripping right now.</div></div>')

    if scores:
        rows = "".join(f'<tr><td>{esc(row["horizon"])}</td><td class="r">{row["n"]}</td>'
                       f'<td class="r">{row["hit_rate"]:.0%}</td>'
                       f'<td class="r {"up" if row["mean_net"] >= 0 else "down"}">{row["mean_net"]:+.2%}</td>'
                       f'<td class="r {"up" if (row["mean_excess"] or 0) >= 0 else "down"}">'
                       f'{pct(row["mean_excess"], 2)}</td></tr>' for row in scores)
        parts.append('<div class="card"><h2>Scorecard</h2><table>'
                     '<tr><th>horizon</th><th class="r">n</th><th class="r">profitable</th>'
                     f'<th class="r">net</th><th class="r">vs BTC</th></tr>{rows}</table>'
                     f'<div class="none">{len(decisions)} scored decisions, {realised} closing trades. '
                     'Net is after the quoted spread; vs BTC is the same money held in Bitcoin.</div></div>')

    parts.append('</div>')
    page = "\n".join(parts)
    with open(OUT_PATH, "w", encoding="utf-8") as handle:
        handle.write(page)
    return OUT_PATH


if __name__ == "__main__":
    print(build())
